import React, { useEffect, useState } from "react";
import { verifyInvoice, money, fmtDate, downloadDocPdf } from "./api.js";
import QrCode from "./QrCode.jsx";
import logo from "./assets/3.png";
import logo1 from "./assets/1.png";
import logo2 from "./assets/2.png";

// Printable invoice document — opened at /invoice?inv=INV-....
// Includes a QR code that links to the verification page so anyone holding the
// printed copy can scan it to confirm authenticity and payment status.
export default function InvoicePage() {
  const ref = new URLSearchParams(window.location.search).get("inv") || "";
  const [state, setState] = useState({
    loading: true,
    error: null,
    invoice: null,
    verifyUrl: null,
    downloading: false,
  });

  useEffect(() => {
    let alive = true;
    verifyInvoice(ref)
      .then(
        (data) =>
          alive &&
          setState({
            loading: false,
            invoice: data.invoice,
            verifyUrl: data.verifyUrl,
          }),
      )
      .catch(
        (err) => alive && setState({ loading: false, error: err.message }),
      );
    return () => {
      alive = false;
    };
    }, [ref]);

  // Browser tab / PDF filename states the document type explicitly
  useEffect(() => {
    document.title = state.invoice
      ? `Payment Invoice ${state.invoice.invoiceNumber} — KSPVIB`
      : state.error
        ? "Invoice unavailable — KSPVIB"
        : "Invoice — KSPVIB";
  }, [state]);

  return (
    <div className="doc-page">
      <div className="printbar">
        <button
          disabled={state.downloading}
          onClick={async () => {
            try {
              setState((s) => ({ ...s, downloading: true }));
              await downloadDocPdf("invoice", ref);
            } catch (err) {
              alert(`Download failed: ${err.message}`);
            } finally {
              setState((s) => ({ ...s, downloading: false }));
            }
          }}
        >
          {state.downloading ? "Preparing…" : "Download PDF"}
        </button>
        <button onClick={() => window.print()}>Print</button>
        <a href="/verify">← Back to verification</a>
      </div>
      <article className="doc-paper invoice-doc">
        {state.loading && <div className="notice">Loading invoice…</div>}
        {state.error && (
          <div className="notice">
            <strong>Invoice unavailable.</strong> {state.error}
          </div>
        )}
        {state.invoice && (
          <InvoiceDoc {...state.invoice} verifyUrl={state.verifyUrl} />
        )}
      </article>
    </div>
  );
}

function InvoiceDoc({ verifyUrl, ...inv }) {
  const paid = inv.status === "PAID";
  return (
    <>
      <div className="rhead">
        <div className="logo-row">
          <img className="logo-img" src={logo2} alt="Ministry of Education logo" />
          <img className="logo-img" src={logo} alt="KSPVIB logo" />
          <img className="logo-img" src={logo1} alt="Kano State Government logo" />
        </div>
        <div className="gov">KANO STATE GOVERNMENT</div>
        <div className="ministry">MINISTRY OF EDUCATION</div>
        <div className="board">
          KANO STATE PRIVATE AND VOLUNTARY INSTITUTIONS BOARD (KSPVIB)
        </div>
        <div className="tagline">Quality Education for a Brighter Kano</div>
      </div>
      <div className="title-row">
        <div>
          <div className="title">Payment Invoice</div>
          <p className="intro">
            This invoice was generated by the Kano State Private and Voluntary
            Institutions Board (KSPVIB).
          </p>
        </div>
        <div className="meta">
          <div>Invoice No.</div>
          <div className="no">{inv.invoiceNumber}</div>
          <div>Date: {fmtDate(inv.issued)}</div>
          <span className={`pill ${paid ? "paid" : "unpaid"}`}>
            {paid ? "PAID" : "UNPAID"}
          </span>
        </div>
      </div>
      <div className="boxes">
        <div className="box">
          <div className="cap">BILLED TO</div>
          <div className="val school">{inv.school}</div>
          <div className="sub">LGA: {inv.lga || "—"}</div>
          <div className="sub">School Grade: {inv.grade || "—"}</div>
          <div className="sub">Term: {inv.term || "—"}</div>
        </div>
        <Box cap="CATEGORY" val={inv.paymentType} />
        <Box cap="PROPRIETOR" val={inv.proprietor || "—"} />
      </div>
      <table>
        <thead>
          <tr>
            <th className="col-idx">#</th>
            <th>DESCRIPTION</th>
            <th className="col-amt">AMOUNT (₦)</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>{inv.description}</td>
            <td className="amt">{money(inv.amount)}</td>
          </tr>
        </tbody>
      </table>
      <div className="total">
        <span>Total Amount</span>
        <strong>{money(inv.amount)}</strong>
      </div>
      <div className="bottom">
        <div className="thanks">
          Make payment through the KSPVIB portal.
          <br />
          A receipt becomes available once payment is confirmed.
          <div className="foot-note">
            Kano State Ministry of Education
            <br />
            Private and Voluntary Institutions Board (KSPVIB)
          </div>
        </div>
        <div className="qr-block">
          <QrCode value={verifyUrl} />
          <a className="verify-url" href={verifyUrl}>
            {verifyUrl}
          </a>
        </div>
      </div>
    </>
  );
}

function Box({ cap, val }) {
  return (
    <div className="box">
      <div className="cap">{cap}</div>
      <div className="val">{val}</div>
    </div>
  );
}
